version: 2
defaults: &defaults
  working_directory: /go/src/github.com/rerorero/graph

golang: &golang
  <<: *defaults
  docker:
    - image: golang

jobs:
  build:
    <<: *golang
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d vendor ]; then
              make dep-vendor-only
            fi
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/rerorero/graph/vendor
      - persist_to_workspace:
          root: /go/src/github.com/rerorero/graph
          paths:
            - "vendor/*"
      - run: make build

  test:
    <<: *golang
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/rerorero/graph
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
      - test:
          requires:
            - build
