version: 2

golang: &golang
  working_directory: /go/src/github.com/rerorero/prerogel
  docker:
    - image: golang:1.12

jobs:
  test:
    <<: *golang
    steps:
      - checkout
      - run: make build
      - run: make coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
